Repository thefrontside/simulacrum, pull requests merged in 2021-08, with the labels that each got.

#112 Tiny enhancements to READMEs
  README.md
  packages/auth0/README.md
Labels: documentation

#116 use `email` in the id token data, not `mail`
  .changes/email-typo.md
  package-lock.json
  packages/auth0/src/handlers/auth0-handlers.ts
  packages/auth0/test/auth0.test.ts
Labels: bug

#110 Publish New Versions
  .changes/bare-export-person-scenario.md
  .changes/email-typo.md
  .changes/error.md
  examples/nextjs-with-auth0-react/CHANGELOG.md
  examples/nextjs-with-auth0-react/package.json
  examples/nextjs-with-nextjs-auth0/CHANGELOG.md
  examples/nextjs-with-nextjs-auth0/package.json
  package-lock.json
  packages/auth0/CHANGELOG.md
  packages/auth0/package.json
Labels: version updates

#120 Publish New Versions
  .changes/bump-effection-past-missing-dist.md
  .changes/no-spawn-dead-task.md
  .changes/npx-auth0-simulator.md
  examples/nextjs-with-auth0-react/CHANGELOG.md
  examples/nextjs-with-auth0-react/package.json
  examples/nextjs-with-nextjs-auth0/CHANGELOG.md
  examples/nextjs-with-nextjs-auth0/package.json
  package-lock.json
  packages/auth0/CHANGELOG.md
  packages/auth0/package.json
  packages/client/CHANGELOG.md
  packages/client/package.json
  packages/server/CHANGELOG.md
  packages/server/package.json
Labels: version updates
